networks:
  rtsp-server:

services:
  rtsp_server:
    image: bluenviron/mediamtx
    networks:
      - rtsp-server
    ports:
      - ${RTSP_PORT}:8554
      - 1935:1935

  stream:
    image: baicontainers/rtsp-feed
    networks:
      - rtsp-server
    volumes:
      - ${VOLUME_MOUNT}
    depends_on:
      - rtsp_server
    environment:
      - STREAM_ENDPOINT=${STREAM_ENDPOINT}
      - FILE_PATH=${FILE_PATH}
